language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
script:
  - "rake lint"
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
matrix:
  allow_failures:
    - rvm: ruby-head
gemfile: .gemfile
notifications:
  email:
    - stas.alekseev@gmail.com
