name    'athenahealth-nswl'
version '0.1.0'
source 'https://github.com/athenahealth/puppet-nswl'
author 'salekseev'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring nswl'
description 'Module for managing and configuring NSweblog for Citrix Netscaler'
project_page 'https://github.com/athenahealth/puppet-nswl'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
